CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at timestamp
);

CREATE UNIQUE INDEX users_email_uq_active
ON users(email)
WHERE deleted = false;

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(128) NOT NULL,
    annotation VARCHAR(256) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    created_on TIMESTAMP NOT NULL,
    published_on TIMESTAMP,
    event_date TIMESTAMP NOT NULL,
    paid BOOLEAN NOT NULL,
    request_moderation BOOLEAN NOT NULL,
    participant_limit INTEGER NOT NULL,
    state VARCHAR(32) NOT NULL,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    initiator_id BIGINT NOT NULL REFERENCES users(id),
    category_id BIGINT NOT NULL REFERENCES categories(id)
);

CREATE INDEX idx_events_created_on
ON events(created_on);

CREATE INDEX idx_events_state_event_date
ON events(state, event_date);

CREATE INDEX idx_events_published_event_date
ON events(event_date)
WHERE state = 'PUBLISHED';

CREATE INDEX idx_events_event_date
ON events(event_date);

CREATE INDEX idx_events_category_id
ON events(category_id);

CREATE INDEX idx_events_initiator_id
ON events(initiator_id);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(128) NOT NULL,
    pinned BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS events_compilations (
    compilation_id BIGINT REFERENCES compilations(id) ON DELETE CASCADE,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    created TIMESTAMP NOT NULL,
    event_id BIGINT NOT NULL REFERENCES events(id),
    requester_id BIGINT NOT NULL REFERENCES users(id),
    CONSTRAINT uq_request_event_requester UNIQUE (event_id, requester_id)
);

CREATE INDEX idx_participation_requests_event_id
ON participation_requests(event_id);

CREATE INDEX idx_participation_requests_requester_id
ON participation_requests(requester_id);