CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(2000) NOT NULL,
    created_on TIMESTAMP NOT NULL,
    updated_on TIMESTAMP,
    deleted_on TIMESTAMP,
    event_id BIGINT NOT NULL REFERENCES events(id),
    author_id BIGINT NOT NULL REFERENCES users(id),
    CONSTRAINT comment_text_not_blank
        CHECK (char_length(btrim(text)) >= 1)
);

CREATE INDEX IF NOT EXISTS idx_comments_event_id
    ON comments(event_id);

CREATE INDEX IF NOT EXISTS idx_comments_author_id
    ON comments(author_id);

CREATE INDEX IF NOT EXISTS idx_comments_event_created_active
    ON comments (event_id, created_on DESC)
    WHERE deleted_on IS NULL;

CREATE INDEX IF NOT EXISTS idx_comments_author_created_active
    ON comments (author_id, created_on DESC)
    WHERE deleted_on IS NULL;