CREATE TABLE IF NOT EXISTS endpoint_hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(64) NOT NULL,
    uri VARCHAR(128) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    created TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS endpoint_hits_uri_cr_idx
ON endpoint_hits (uri, created);

CREATE INDEX IF NOT EXISTS endpoint_hits_cr_idx
ON endpoint_hits(created);